---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/MartinBasti/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-fix-integration-service-prometheus-exporters
