resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=d21ac53c34f5ca331b2844a238b874eba19b0e6d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/martinbasti/stonesoup
    newTag: integration-service-2
namespace: integration-service
patches:
  - ./manager_resources_patch.yaml
